sudo: required
language: generic
services:
  - docker

script:
  - docker build -t jvmachado/bca-conversor-client ./client
  - docker build -t jvmachado/bca-conversor-server ./server 
  - docker build -t jvmachado/bca-conversor-nginx ./nginx 
  #Login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push jvmachado/bca-conversor-client
  - docker push jvmachado/bca-conversor-server
  - docker push jvmachado/bca-conversor-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "bca-conversor"
  env: "BcaConversor-env"
  bucket_name: "elasticbeanstalk-us-east-2-238812045852"
  bucket_path: "bca-conversor"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"